Add printbox-text to Dune.
To fix building:
```
       > File "src/Reporter.re", line 32, characters 40-60:
       > 32 |   PrintBox.(frame(grid_text(table))) |> PrintBox_text.output(stdout);
       >                                              ^^^^^^^^^^^^^^^^^^^^
       > Error: Unbound module PrintBox_text
```
I suppose `printbox` doesn't have to be added because `printbox-text` will propagate it automatically.